const paisContinente = [
  ['Brasil', 'america'],
  ['Afeganistão', 'asia'],
  ['África do Sul', 'africa'],
  ['Albânia', 'europa'],
  ['Alemanha', 'europa'],
  ['Andorra', 'europa'],
  ['Angola', 'africa'],
  ['Antígua e Barbuda', 'america'],
  ['Arábia Saudita', 'asia'],
  ['Argélia', 'africa'],
  ['Argentina', 'america'],
  ['Armênia', 'asia'],
  ['Austrália', 'oceania'],
  ['Áustria', 'europa'],
  ['Azerbaijão', 'asia'],
  ['Bahamas', 'america'],
  ['Bahrein', 'asia'],
  ['Bangladesh', 'asia'],
  ['Barbados', 'america'],
  ['Bélgica', 'europa'],
  ['Belize', 'america'],
  ['Benin', 'africa'],
  ['Butão', 'asia'],
  ['Bielorrússia', 'europa'],
  ['Bolívia', 'america'],
  ['Bósnia e Herzegovina', 'europa'],
  ['Botswana', 'africa'],
  ['Brunei', 'asia'],
  ['Bulgária', 'europa'],
  ['Burkina Faso', 'africa'],
  ['Burundi', 'africa'],
  ['Cabo Verde', 'africa'],
  ['Camarões', 'africa'],
  ['Camboja', 'asia'],
  ['Canadá', 'america'],
  ['Catar', 'asia'],
  ['Cazaquistão', 'asia'],
  ['Chade', 'africa'],
  ['Chile', 'america'],
  ['China', 'asia'],
  ['Chipre', 'europa'],
  ['Colômbia', 'america'],
  ['Comores', 'africa'],
  ['Coreia do Norte', 'asia'],
  ['Coreia do Sul', 'asia'],
  ['Costa do Marfim', 'africa'],
  ['Costa Rica', 'america'],
  ['Croácia', 'europa'],
  ['Cuba', 'america'],
  ['Dinamarca', 'europa'],
  ['Djibouti', 'africa'],
  ['Dominica', 'america'],
  ['Egito', 'africa'],
  ['El Salvador', 'america'],
  ['Emirados Árabes Unidos', 'asia'],
  ['Equador', 'america'],
  ['Eritreia', 'africa'],
  ['Eslováquia', 'europa'],
  ['Eslovênia', 'europa'],
  ['Espanha', 'europa'],
  ['Estados Unidos', 'america'],
  ['Estônia', 'europa'],
  ['Etiópia', 'africa'],
  ['Fiji', 'oceania'],
  ['Filipinas', 'asia'],
  ['Finlândia', 'europa'],
  ['França', 'europa'],
  ['Gabão', 'africa'],
  ['Gâmbia', 'africa'],
  ['Gana', 'africa'],
  ['Geórgia', 'asia'],
  ['Granada', 'america'],
  ['Grécia', 'europa'],
  ['Guatemala', 'america'],
  ['Guiana', 'america'],
  ['Guiné', 'africa'],
  ['Guiné Equatorial', 'africa'],
  ['Guiné-Bissau', 'africa'],
  ['Haiti', 'america'],
  ['Honduras', 'america'],
  ['Hungria', 'europa'],
  ['Iémen', 'asia'],
  ['Ilhas Marshall', 'oceania'],
  ['Índia', 'asia'],
  ['Indonésia', 'asia'],
  ['Irã', 'asia'],
  ['Iraque', 'asia'],
  ['Irlanda', 'europa'],
  ['Islândia', 'europa'],
  ['Israel', 'asia'],
  ['Itália', 'europa'],
  ['Jamaica', 'america'],
  ['Japão', 'asia'],
  ['Jordânia', 'asia'],
  ['Kiribati', 'oceania'],
  ['Kosovo', 'europa'],
  ['Kuwait', 'asia'],
  ['Laos', 'asia'],
  ['Lesoto', 'africa'],
  ['Letônia', 'europa'],
  ['Líbano', 'asia'],
  ['Libéria', 'africa'],
  ['Líbia', 'africa'],
  ['Liechtenstein', 'europa'],
  ['Lituânia', 'europa'],
  ['Luxemburgo', 'europa'],
  ['Madagáscar', 'africa'],
  ['Malásia', 'asia'],
  ['Malawi', 'africa'],
  ['Maldivas', 'asia'],
  ['Mali', 'africa'],
  ['Malta', 'europa'],
  ['Marrocos', 'africa'],
  ['Maurício', 'africa'],
  ['Mauritânia', 'africa'],
  ['México', 'america'],
  ['Mianmar', 'asia'],
  ['Micronésia', 'oceania'],
  ['Moçambique', 'africa'],
  ['Moldávia', 'europa'],
  ['Mônaco', 'europa'],
  ['Mongólia', 'asia'],
  ['Montenegro', 'europa'],
  ['Namíbia', 'africa'],
  ['Nauru', 'oceania'],
  ['Nepal', 'asia'],
  ['Nicarágua', 'america'],
  ['Níger', 'africa'],
  ['Nigéria', 'africa'],
  ['Noruega', 'europa'],
  ['Nova Zelândia', 'oceania'],
  ['Omã', 'asia'],
  ['Países Baixos', 'europa'],
  ['Palau', 'oceania'],
  ['Panamá', 'america'],
  ['Papua Nova Guiné', 'oceania'],
  ['Paquistão', 'asia'],
  ['Paraguai', 'america'],
  ['Peru', 'america'],
  ['Polônia', 'europa'],
  ['Portugal', 'europa'],
  ['Quênia', 'africa'],
  ['Quirguistão', 'asia'],
  ['Reino Unido', 'europa'],
  ['República Centro-Africana', 'africa'],
  ['República Democrática do Congo', 'africa'],
  ['República Dominicana', 'america'],
  ['República do Congo', 'africa'],
  ['República Tcheca', 'europa'],
  ['Romênia', 'europa'],
  ['Ruanda', 'africa'],
  ['Rússia', 'europa'],
  ['Saara Ocidental', 'africa'],
  ['Saint Kitts e Nevis', 'america'],
  ['Saint Vincent e Granadinas', 'america'],
  ['Santa Lúcia', 'america'],
  ['São Marino', 'europa'],
  ['São Tomé e Príncipe', 'africa'],
  ['Seicheles', 'africa'],
  ['Senegal', 'africa'],
  ['Serra Leoa', 'africa'],
  ['Sérvia', 'europa'],
  ['Singapura', 'asia'],
  ['Síria', 'asia'],
  ['Somália', 'africa'],
  ['Sri Lanka', 'asia'],
  ['Suazilândia', 'africa'],
  ['Sudão', 'africa'],
  ['Sudão do Sul', 'africa'],
  ['Suécia', 'europa'],
  ['Suíça', 'europa'],
  ['Suriname', 'america'],
  ['Tailândia', 'asia'],
  ['Taiwan', 'asia'],
  ['Tajiquistão', 'asia'],
  ['Tanzânia', 'africa'],
  ['Timor-Leste', 'asia'],
  ['Togo', 'africa'],
  ['Tonga', 'oceania'],
  ['Trinidad e Tobago', 'america'],
  ['Tunísia', 'africa'],
  ['Turcomenistão', 'asia'],
  ['Turquia', 'europa'],
  ['Tuvalu', 'oceania'],
  ['Ucrânia', 'europa'],
  ['Uganda', 'africa'],
  ['Uruguai', 'america'],
  ['Uzbequistão', 'asia'],
  ['Vanuatu', 'oceania'],
  ['Vaticano', 'europa'],
  ['Venezuela', 'america'],
  ['Vietnã', 'asia'],
  ['Zâmbia', 'africa'],
  ['Zimbábue', 'africa'],
]

// Sortear número
function sortearNumero() {
  return Math.floor(Math.random() * 194)
}

let numeroSorteado = sortearNumero()

// Inserir o nome do país sorteado no SPAN
const pais = document.getElementById('pais')
pais.textContent = `${paisContinente[numeroSorteado][0]}`

// Verificar o botão clicado
const buttons = document.querySelectorAll('.opcoes button')

buttons.forEach((button) => {
  button.addEventListener('click', (event) => {
    const value = event.target.value

    // Exibir erro ou acerto
    if (value === paisContinente[numeroSorteado][1]) {
      alert(`Você acertou!: ${value}`)
    } else {
      alert(`Você errou!: ${paisContinente[numeroSorteado][1]}`)
    }

    // Sortear e exibir um novo país
    numeroSorteado = sortearNumero()
    pais.textContent = `${paisContinente[numeroSorteado][0]}`
  })
})
